[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["dgli"]

[project]
name = "CloSE"
version = "0.0.1"
dependencies = [
    "numpy>=1.26.2",
    "matplotlib>=3.9.1",
    "scipy>=1.13.1",
    "scikit-learn>=1.6.0"
]
